### Numpy array operations:-----

In [2]:
import numpy as np

In [4]:
# arr = np.arange(11)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:", arr[1:5])  # Slicing from index 1 to 4
print("Every second element:", arr[::2])  # Every second element
print("Reversed array:", arr[::-1])  # Reversing the array
print("Last three elements:", arr[-3:])  # Last three elements


Basic Slicing: [2 3 4 5]
Every second element: [1 3 5 7 9]
Reversed array: [10  9  8  7  6  5  4  3  2  1]
Last three elements: [ 8  9 10]


In [11]:
arr_2d = np.array([ [1,2,3]
                   ,[4,5,6]
                   ,[7,8,9]])

print ("Specific Element (2,1):", arr_2d[2,1])  # Element at row 2, column 1
print ("Row 1:", arr_2d[1,:])  # Entire row 1
print ("Column 2:", arr_2d[:,2])  # Entire column 2
print ("Sub-array:\n", arr_2d[0:2, 0:3])  # Sub-array from rows 0-1 and columns 0-1

Specific Element (2,1): 8
Row 1: [4 5 6]
Column 2: [3 6 9]
Sub-array:
 [[1 2 3]
 [4 5 6]]


### Sorting:

In [ ]:
unsorted_array = np.array([3, 7, 2, 1, 9, 4])
print("Sorted array:",np.sort(unsorted_array))  # Sorting the array

# Note: The original unsorted_array remains unchanged

arr_2d_unsorted = np.array([[3, 7, 2],
                            [1, 9, 4],  
                            [6, 5, 8]])
print("Sorted along rows:\n", np.sort(arr_2d_unsorted, axis=1))  # Sorting along rows
print("Sorted along columns:\n", np.sort(arr_2d_unsorted, axis=0))  # Sorting along columns

Sorted array: [1 2 3 4 7 9]
Sorted along rows:
 [[2 3 7]
 [1 4 9]
 [5 6 8]]


### Filter:

In [13]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)


Even numbers: [ 2  4  6  8 10 12 14]


### Filter_With_Mask:

In [14]:
mask = numbers > 5
print("Numbers greater than 5:",numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10 11 12 13 14 15]


### Fancy_Indexing VS np.where()

In [ ]:
indices = [1, 3, 5, 7]
print("Elements at indices 1, 3, 5, 7:", numbers[indices])

where_result = np.where(numbers > 10)
print(where_result)
print("Elements greater than 10:", numbers[where_result])

Elements at indices 1, 3, 5, 7: [2 4 6 8]
(array([10, 11, 12, 13, 14]),)
Indices of elements greater than 10: [10 11 12 13 14]
Elements greater than 10: [11 12 13 14 15]


In [23]:
condition_array = np.array([True, False, True, False, True, False, True, False, True, False, True, False, True, False, True])
print("Elements where condition is True:", numbers[condition_array])

condition_array = np.where(numbers % 3 == 0, True, False)
print("Elements divisible by 3:", numbers[condition_array])

condition_array2 = np.where(numbers > 5, numbers*2, numbers)
print("Doubled elements greater than 5:", condition_array2)
# so by using np.where we can create complex conditions and manipulate arrays based on those conditions. and also filter elements based on multiple criteria.
# like  if(numbers > 5){
#     numbers*2
# } else {
#     numbers
# }


Elements where condition is True: [ 1  3  5  7  9 11 13 15]
Elements divisible by 3: [ 3  6  9 12 15]
Doubled elements greater than 5: [ 1  2  3  4  5 12 14 16 18 20 22 24 26 28 30]


### Adding & Removing Data

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
# now we have to combine these two arrays based on a condition
combined = arr1 + arr2
print("Combined array:", combined)
# Output: [11 22 33 44 55]
# but we want to add one after another using a concatenation
combined1 = np.concatenate((arr1, arr2))
print("Concatenated array:", combined1)
# Output: [ 1  2  3  4  5 10 20 30 40 50]
# so here we can see the difference between addition and concatenation of arrays.


Combined array: [11 22 33 44 55]
Concatenated array: [ 1  2  3  4  5 10 20 30 40 50]


### Array_Compatibility:

In [25]:
# we are going to ue this method farther in data science and machine learning projects.
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("Compatibility Shapes: ",a.shape == b.shape)  # True
print("Compatibility Shapes: ",a.shape == c.shape)  # False

Compatibility Shapes:  True
Compatibility Shapes:  False


### Adding_Row

In [27]:
original = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print("Original array:\n", original)

new_row = np.array([[9, 10, 11, 12]])
with_new_row = np.vstack((original,new_row)) # Vertical stacking: where using vstack we can add rows to the array

print("After adding new row:\n", with_new_row)

new_column = np.array([[13],[14]])
with_new_column = np.hstack((original,new_column)) # Horizontal stacking: where using hstack we can add columns to the array
print("After adding new column:\n", with_new_column)

Original array:
 [[1 2 3 4]
 [5 6 7 8]]
After adding new row:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After adding new column:
 [[ 1  2  3  4 13]
 [ 5  6  7  8 14]]


In [ ]:
# to delete something we use this method....

arr = np.array([2,3,5,1,6])
deleted = np.delete(arr,2) #here we have to give one arg (the array name) and another arg( arr: ndarray[tuple[Any, ...], dtype[Any]]  )

print("Array after deletion: ",deleted)

Array after deletion:  [2 3 1 6]
