## #Numpy Basics:
 


## Learn about numpy:

In [4]:
import numpy as np

### creating array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [ ]:
py_list = [7, 8, 9]
print("Python List:", py_list * 2)

np_array = np.array(py_list)
print("Converted NumPy Array:", np_array * 2)



import time
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List Operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


Python List: [7, 8, 9, 7, 8, 9]
Converted NumPy Array: [14 16 18]

 List Operation time:  0.07606029510498047

 List operation time:  0.01759195327758789


### Creating array from scratch:

In [20]:
zeros = np.zeros((3,4))
print("Zeros array: \n",zeros)

ones = np.ones((4,2))
print("Ones array: \n", ones)

full = np.full((5,3),7)
print("full array: \n",full)

random = np.random.random((3,3))
print("randoms array: \n",random)

sequence = np.arange(0,100,2)
print("Sequence array: \n",sequence)



Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
full array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
randoms array: 
 [[0.04605619 0.71208787 0.612307  ]
 [0.88185945 0.01859905 0.82031947]
 [0.48894906 0.88564899 0.6370275 ]]
Sequence array: 
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


### Vector, Matrix and Tensor:

In [23]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],
[4,5,6]])
print("Matrix : \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]],
                   [[9,0],[6,9]]])
print("Tensor: \n",tensor)

Vector: 
 [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 0]
  [6 9]]]


### Array props:

In [24]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape: \n",arr.shape)
print("Dimension: \n",arr.ndim)
print("Size: \n",arr.size)
print("Dtype: \n",arr.dtype)

Shape: 
 (2, 3)
Dimension: 
 2
Size: 
 6
Dtype: 
 int64


### Array Reshaping:

In [28]:
arr = np.arange(12)
print("Original array: ",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array: \n",reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: \n",flattened)

raveled = reshaped.ravel() #this ravel return view, instead of copy
print("raveled array: \n",raveled)

transpose = reshaped.T
print("Transpose array: \n",transpose)



Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
